# Generated by Django 4.0 on 2021-12-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='numer faktury')),
                ('payment_date', models.DateField(verbose_name='termin płatności')),
                ('supplier', models.CharField(default='', max_length=50, verbose_name='nazwa firmy')),
                ('amount', models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='kwota')),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
